
------------------------------------------------------------------------------------
miércoles, 29 de noviembre de 2023 2:27:27.11 p. m.
The instance of entity type 'UsuarioModel' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.

------------------------------------------------------------------------------------
miércoles, 29 de noviembre de 2023 2:28:02.76 p. m.
The instance of entity type 'UsuarioModel' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.

------------------------------------------------------------------------------------
miércoles, 29 de noviembre de 2023 7:07:49.55 p. m.
An error occurred while saving the entity changes. See the inner exception for details.

------------------------------------------------------------------------------------
miércoles, 29 de noviembre de 2023 7:35:07.55 p. m.
An error occurred while saving the entity changes. See the inner exception for details.

------------------------------------------------------------------------------------
miércoles, 29 de noviembre de 2023 7:35:32.14 p. m.
An error occurred while saving the entity changes. See the inner exception for details.

------------------------------------------------------------------------------------
miércoles, 29 de noviembre de 2023 7:36:56.26 p. m.
An error occurred while saving the entity changes. See the inner exception for details.

------------------------------------------------------------------------------------
miércoles, 29 de noviembre de 2023 8:05:46.00 p. m.
An error occurred while saving the entity changes. See the inner exception for details.

------------------------------------------------------------------------------------
miércoles, 29 de noviembre de 2023 8:06:09.08 p. m.
An error occurred while saving the entity changes. See the inner exception for details.

------------------------------------------------------------------------------------
miércoles, 29 de noviembre de 2023 8:06:22.84 p. m.
An error occurred while saving the entity changes. See the inner exception for details.

------------------------------------------------------------------------------------
miércoles, 29 de noviembre de 2023 8:06:36.97 p. m.
An error occurred while saving the entity changes. See the inner exception for details.

------------------------------------------------------------------------------------
miércoles, 29 de noviembre de 2023 8:08:28.44 p. m.
An error occurred while saving the entity changes. See the inner exception for details.

------------------------------------------------------------------------------------
miércoles, 29 de noviembre de 2023 8:10:14.21 p. m.
An error occurred while saving the entity changes. See the inner exception for details.
